Added jumping number program in python
keshavsingh4522/Python pull request #134
Opened 2021-05-13 06:25 UTC by prathimacode-hub

This program checks whether the number input given is jumping number or not.

2021-05-13 13:07 UTC, keshavsingh4522 requested changes

2021-05-13 13:31 UTC, prathimacode-hub commented on jumping_number.py
> +        res = 0
Loop stops in both the conditions. It states to check if the user given input is jumping number or not. I have attached screenshot to verify the same. 

[Screenshot](https://github.com/prathimacode-hub/prathimacode-hub/blob/main/misc/Screenshot1.png)

2021-05-14 00:42 UTC, keshavsingh4522 commented on jumping_number.py
> +        res = 0
I am not saying that loop will not stop.

2021-05-14 00:43 UTC, keshavsingh4522 approved these changes

2021-05-14 00:43 UTC, merged